title: "Léa Cassé"
name: "Léa Cassé"
subtitle: "PhD | Quantum Machine Learning for Data Streams"
description: "Quantum re-uploading units, time-series & risk forecasting."
url: "https://leacasse.github.io"
baseurl: "/academic-page"   # car ton repo s’appelle academic-page
repository: "leacasse/academic-page"
locale: "fr-NZ"
# Sidebar
author:
  name: "Léa Cassé"
  avatar: "/images/lea.jpg"
  bio: "PhD candidate as part of the TAIAO project at the Artificial Intelligence Institute, University of Waikato (NZ) and École Polytechnique, IP Paris (France)."
  location: "New Zealand and France"
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/..."
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/..."
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/leacasse"
collections:
  publications:
    output: true
    permalink: /publication/:title/
  talks:
    output: true
    permalink: /talk/:title/

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: single
  - scope:
      path: ""
      type: talks
    values:
      layout: single
